apiVersion: apps/v1
kind: Deployment
metadata:
  name: rso-microservice-tip-vozil-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rso-microservice-tip-vozil
  template:
    metadata:
      labels:
        app: rso-microservice-tip-vozil
    spec:
      containers:
        - image: slocomptech/rso-microservice-tip-vozil:1.0.4
          name: rso-microservice-tip-vozil
          env:
            - name: DOCS
              value: 'true'
            - name: NODE_ENV
              value: production
            - name: PORT
              value: '3000'
            - name: LOG_REQUESTS
              value: 'true'
            - name: HTTP_TIMEOUT
              value: '5000'
            - name: CONSUL_HOST
              valueFrom:
                secretKeyRef:
                  name: rso-secrets
                  key: CONSUL_HOST
            - name: KAFKA_BROKER
              valueFrom:
                secretKeyRef:
                  name: rso-secrets
                  key: KAFKA_BROKER
            - name: RAPIDAPI_HOST
              valueFrom:
                secretKeyRef:
                  name: rso-secrets
                  key: RAPIDAPI_HOST
            - name: RAPIDAPI_KEY
              valueFrom:
                secretKeyRef:
                  name: rso-secrets
                  key: RAPIDAPI_KEY
            - name: TYPEORM_HOST
              valueFrom:
                secretKeyRef:
                  name: rso-secrets
                  key: TYPEORM_HOST
            - name: TYPEORM_PORT
              valueFrom:
                secretKeyRef:
                  name: rso-secrets
                  key: TYPEORM_PORT
            - name: TYPEORM_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rso-secrets
                  key: TYPEORM_USERNAME
            - name: TYPEORM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rso-secrets
                  key: TYPEORM_PASSWORD
          ports:
            - containerPort: 3000
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: rso-microservice-tip-vozil
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: rso-microservice-tip-vozil